// Real, date-anchored admissions calendar — the deterministic source for the
// Timeline. Dates live HERE in code (never generated by the AI, which would
// hallucinate or go stale) and are computed against "today" + the student's
// graduation year, so the same profile always yields the same plan.
//
// ⚠️ VERIFY ANNUALLY. SAT sittings and competition deadlines below are the
// curated 2026–27 cycle. They are presented in the UI as "confirm on the
// official site" with a register link — but the founder should re-check these
// against College Board / each competition each year and bump them. Sources are
// linked per item. Keeping them roughly right is far better than the old generic
// "register for the next SAT" with no date at all.

import type { FacultyValue } from "@/lib/data/faculties";

// ── SAT sittings (digital SAT, international) ─────────────────────────────────
// test = test day; regDeadline = standard registration deadline.
// Source: https://satsuite.collegeboard.org/sat/dates-deadlines
export type SatSitting = { test: string; regDeadline: string }; // ISO YYYY-MM-DD

export const SAT_SITTINGS: SatSitting[] = [
  { test: "2026-08-29", regDeadline: "2026-08-14" },
  { test: "2026-10-03", regDeadline: "2026-09-19" },
  { test: "2026-11-07", regDeadline: "2026-10-24" },
  { test: "2026-12-05", regDeadline: "2026-11-20" },
  { test: "2027-03-13", regDeadline: "2027-02-26" },
  { test: "2027-05-01", regDeadline: "2027-04-16" },
  { test: "2027-06-05", regDeadline: "2027-05-21" },
];

export const SAT_REGISTER_URL =
  "https://satsuite.collegeboard.org/sat/dates-deadlines";

// ── Competitions / olympiads, tagged by field ────────────────────────────────
// `fields: "all"` = relevant to any applicant. `deadline` is the next
// registration/submission deadline for the 2026–27 cycle (VERIFY per source).
export type Competition = {
  id: string;
  name: string;
  fields: FacultyValue[] | "all";
  deadline: string; // ISO YYYY-MM-DD — registration / submission cutoff
  window: string; // human-readable timing of the event itself
  level: "international" | "national" | "regional";
  url: string;
  blurb: string;
};

export const COMPETITIONS: Competition[] = [
  {
    id: "amc",
    name: "AMC 10/12 (math)",
    fields: ["computer_science", "engineering", "natural_sciences"],
    deadline: "2026-10-15",
    window: "Contest in November",
    level: "national",
    url: "https://maa.org/maa-invitational-competitions/",
    blurb: "Gateway to AIME/USAMO — the standard math-talent signal for STEM.",
  },
  {
    id: "usaco",
    name: "USACO (competitive programming)",
    fields: ["computer_science", "engineering"],
    deadline: "2026-12-01",
    window: "Online contests Dec–Mar",
    level: "national",
    url: "https://usaco.org/",
    blurb: "Promote through Bronze→Silver→Gold to prove real CS ability.",
  },
  {
    id: "isef",
    name: "Regeneron ISEF (research)",
    fields: ["natural_sciences", "engineering", "medicine_health", "computer_science"],
    deadline: "2027-02-01",
    window: "Regional fairs Feb–Mar, finals May",
    level: "international",
    url: "https://www.societyforscience.org/isef/",
    blurb: "Original research project — the strongest STEM 'spike' you can build.",
  },
  {
    id: "usabo",
    name: "USABO (biology olympiad)",
    fields: ["medicine_health", "natural_sciences"],
    deadline: "2027-01-15",
    window: "Open exam early February",
    level: "national",
    url: "https://www.usabo-trc.org/",
    blurb: "Top biology signal for pre-med / life-science applicants.",
  },
  {
    id: "decca",
    name: "DECA (business & marketing)",
    fields: ["business_economics"],
    deadline: "2026-11-15",
    window: "Regionals winter, ICDC in April",
    level: "international",
    url: "https://www.deca.org/",
    blurb: "Case-based business competition — leadership + commercial sense.",
  },
  {
    id: "econ-challenge",
    name: "National Economics Challenge",
    fields: ["business_economics", "humanities_social"],
    deadline: "2027-02-15",
    window: "State rounds spring",
    level: "national",
    url: "https://www.councilforeconed.org/national-economics-challenge/",
    blurb: "Team econ contest — a sharp signal for economics applicants.",
  },
  {
    id: "john-locke",
    name: "John Locke Essay Prize",
    fields: ["humanities_social", "law", "business_economics"],
    deadline: "2027-06-30",
    window: "Submissions due end of June",
    level: "international",
    url: "https://www.johnlockeinstitute.com/essay-competition",
    blurb: "Flagship essay prize for humanities, law, philosophy and econ.",
  },
  {
    id: "scholastic",
    name: "Scholastic Art & Writing Awards",
    fields: ["arts_design", "humanities_social"],
    deadline: "2026-12-01",
    window: "Deadlines Dec–Jan by region",
    level: "national",
    url: "https://www.artandwriting.org/",
    blurb: "The most recognized awards for creative arts and writing.",
  },
  {
    id: "mun",
    name: "Model UN conference",
    fields: ["humanities_social", "law", "business_economics"],
    deadline: "2026-10-01",
    window: "Conferences run year-round",
    level: "regional",
    url: "https://www.nmun.org/",
    blurb: "Diplomacy, public speaking and current-affairs depth.",
  },
];

// ── Date helpers (UTC, date-only — no timezone drift) ─────────────────────────
function toUTC(d: Date | string): number {
  const x = typeof d === "string" ? new Date(d + "T00:00:00Z") : d;
  return Date.UTC(x.getUTCFullYear(), x.getUTCMonth(), x.getUTCDate());
}

/** Whole days from `from` to `to` (negative if `to` is in the past). */
export function daysBetween(from: Date | string, to: Date | string): number {
  return Math.round((toUTC(to) - toUTC(from)) / 86_400_000);
}

export function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00Z").toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

// ── The engine: build a dated study plan from today + the student's profile ───
export type StudyPlanInputs = {
  today: Date;
  graduationYear?: number;
  faculties: string[];
  satScore?: number;
};

export type SatStep = {
  test: string;
  regDeadline: string;
  daysToDeadline: number;
  registrationOpen: boolean; // deadline hasn't passed
  lastBeforeApps: boolean; // last sitting whose scores land before app deadlines
};

export type CompetitionStep = Competition & { daysToDeadline: number };

export type Deadline = { label: string; date: string; daysLeft: number };

export type StudyPlan = {
  cycleLabel: string | null;
  satScore?: number;
  satStrong: boolean; // already a strong score → SAT is optional polish
  satSteps: SatStep[];
  competitions: CompetitionStep[];
  deadlines: Deadline[];
};

const SAT_STRONG = 1500;

export function buildStudyPlan({
  today,
  graduationYear,
  faculties,
  satScore,
}: StudyPlanInputs): StudyPlan {
  // Application-deadline window from graduation year. A "Class of G" student
  // applies in the fall before — Early ≈ Nov 1 (G-1), Regular ≈ Jan 5 (G).
  let deadlines: Deadline[] = [];
  let earlyDeadlineISO: string | null = null;
  let cycleLabel: string | null = null;
  if (graduationYear) {
    earlyDeadlineISO = `${graduationYear - 1}-11-01`;
    const regularISO = `${graduationYear}-01-05`;
    cycleLabel = `Class of ${graduationYear} · applying in the ${graduationYear - 1}–${String(
      graduationYear
    ).slice(2)} cycle`;
    deadlines = [
      { label: "Early Action / Decision deadline", date: earlyDeadlineISO, daysLeft: daysBetween(today, earlyDeadlineISO) },
      { label: "Regular Decision deadline", date: regularISO, daysLeft: daysBetween(today, regularISO) },
    ].filter((d) => d.daysLeft >= -30); // hide deadlines well in the past
  }

  // SAT sittings whose registration is still open, soonest first. The "last
  // before apps" sitting is the latest test ≥ 3 weeks before the early deadline
  // (scores need time to arrive).
  const openSittings = SAT_SITTINGS.filter(
    (s) => daysBetween(today, s.regDeadline) >= 0
  );
  let lastBeforeIdx = -1;
  if (earlyDeadlineISO) {
    for (let i = 0; i < openSittings.length; i++) {
      if (daysBetween(openSittings[i].test, earlyDeadlineISO) >= 21) lastBeforeIdx = i;
    }
  }
  const satSteps: SatStep[] = openSittings.slice(0, 3).map((s, i) => ({
    test: s.test,
    regDeadline: s.regDeadline,
    daysToDeadline: daysBetween(today, s.regDeadline),
    registrationOpen: true,
    lastBeforeApps: i === lastBeforeIdx,
  }));

  // Competitions matching the student's field(s), nearest deadline first.
  const fac = new Set(faculties);
  const competitions: CompetitionStep[] = COMPETITIONS.filter(
    (c) => c.fields === "all" || c.fields.some((f) => fac.has(f))
  )
    .filter((c) => daysBetween(today, c.deadline) >= 0)
    .map((c) => ({ ...c, daysToDeadline: daysBetween(today, c.deadline) }))
    .sort((a, b) => a.daysToDeadline - b.daysToDeadline)
    .slice(0, 4);

  return {
    cycleLabel,
    satScore,
    satStrong: satScore != null && satScore >= SAT_STRONG,
    satSteps,
    competitions,
    deadlines,
  };
}
