// Real, date-anchored admissions calendar — the deterministic source for the
// Timeline. Dates live HERE in code (never generated by the AI, which would
// hallucinate or go stale) and are computed against "today" + the student's
// graduation year, so the same profile always yields the same plan.
//
// ⚠️ VERIFY ANNUALLY. SAT sittings and competition deadlines below are the
// curated 2026–27 cycle. They are presented in the UI as "confirm on the
// official site" with a register link — but the founder should re-check these
// against College Board / each competition each year and bump them. Sources are
// linked per item. Keeping them roughly right is far better than the old generic
// "register for the next SAT" with no date at all.
//
// The same applies to `cost`/`costDetail` (see CostModel below): fees drift
// between cycles, so the figures below are approximate by design and the UI
// always pairs them with "confirm on the official page". Re-check them in the
// annual pass alongside the dates — a stale "free" is the one error that costs
// us a student's trust outright.
//
// Competition dates hand-verified against official sources on 2026-06-27. Where
// an exact 2026–27 date wasn't yet published, the entry uses the competition's
// stable annual pattern (noted in the window text) — re-check before relying.

import type { FacultyValue } from "@/lib/data/faculties";
import type { PartnerRef } from "@/lib/data/partners";
import {
  checkEligibility,
  gradeFromGraduationYear,
  parseEligibility,
  plausibleAgeForGrade,
  type EligibilityGate,
} from "@/lib/data/eligibility";
import { COMPETITIONS } from "./competitions-data";

// ── SAT sittings (digital SAT, international) ─────────────────────────────────
// test = test day; regDeadline = standard registration deadline.
// Source: https://satsuite.collegeboard.org/sat/dates-deadlines
export type SatSitting = { test: string; regDeadline: string }; // ISO YYYY-MM-DD

export const SAT_SITTINGS: SatSitting[] = [
  { test: "2026-08-22", regDeadline: "2026-08-07" },
  { test: "2026-09-12", regDeadline: "2026-08-28" },
  { test: "2026-10-03", regDeadline: "2026-09-18" },
  { test: "2026-11-07", regDeadline: "2026-10-23" },
  { test: "2026-12-05", regDeadline: "2026-11-20" },
  { test: "2027-03-06", regDeadline: "2027-02-19" },
  { test: "2027-05-01", regDeadline: "2027-04-16" },
  { test: "2027-06-05", regDeadline: "2027-05-21" },
];

export const SAT_REGISTER_URL =
  "https://satsuite.collegeboard.org/sat/dates-deadlines";

// ── Competitions / olympiads, tagged by field, category and tier ──────────────
// `fields: "all"` = relevant to any applicant. `deadline` is the next
// registration/submission deadline for the 2026–27 cycle (VERIFY per source).
//
// `category` and `tier` drive the Extracurriculars section:
//  • category — "olympiad" (subject olympiads: math/physics/bio/CS/…) vs.
//    "competition" (everything else contest-like: research fairs, essays, MUN…).
//  • tier — how hard/prestigious the prize is, which is what we match to the
//    student's strength: "accessible" (entry-level, build experience),
//    "selective" (national-calibre), "elite" (international flagship — the
//    "one clean win" a strong applicant should chase).
// Both are optional on the TYPE so live rows from a DB that predates the columns
// still validate; `competitionTier`/`competitionCategory` supply a sane default.
export type CompetitionLevel = "international" | "national" | "regional";
// The Opportunities pool is designed to GROW well beyond competitions: courses,
// research programs and summer schools/programs are next. The category union is
// pre-widened so adding them later is data-only (the UI filter derives its tabs
// from the categories actually present). v1 only populates competition/olympiad.
/**
 * The kinds of opportunity, as ONE list.
 *
 * It used to be a bare union, and the same five strings were then restated in
 * the partner form's Zod enum, in the admin quick-add's const, and in the
 * form's option list. Nothing made them agree; adding a sixth kind broke three
 * of them, which is how we found out. Server-side validators derive from this
 * array, so a new kind is one edit and the compiler finds the rest.
 */
export const COMPETITION_CATEGORIES = [
  "competition",
  "olympiad",
  "course",
  "research_program",
  "summer_program",
  // A PLACE rather than an event: a forum, a club network, a citizen-science
  // platform, an open-source month. The distinguishing fact is that there is
  // nothing to win and usually nothing to miss — you join, and you keep going —
  // so almost every row here is `alwaysOpen`.
  //
  // It earns its own kind because "where do I find people doing this" is a
  // different question from "what can I enter", and filing it under
  // `competition` answered neither. It is also the honest answer for a student
  // who is twelve, or has no money, or lives somewhere none of the programmes
  // reach: joining costs nothing and starts today.
  "community",
  // A TRY, not an entry. A job simulation is unpaid, ungraded, has no deadline
  // and nothing to win: you do the actual tasks of a job for a few hours and
  // find out whether you can stand it. That is a different question from every
  // other kind here, and it is the best-evidenced answer we have to "what do I
  // want to study" — the self-efficacy literature names simulations directly,
  // and the platforms report completers as roughly twice as likely to be hired.
  //
  // We LINK OUT and never build these (release 3, PLANNER_PLAN.md §3).
  "simulation",
] as const;

export type CompetitionCategory = (typeof COMPETITION_CATEGORIES)[number];
export type CompetitionTier = "accessible" | "selective" | "elite";

// ── Cost & accessibility ──────────────────────────────────────────────────────
// The second question after "can I enter this" is "what does it cost me", and
// getting it wrong is the fastest way to lose a student's trust: a card that
// says "free" and ends in a paywalled certificate reads as a lie, even when the
// learning really was free. So money is a FIRST-CLASS field on every card, not a
// footnote — and the distinction the catalog has to carry is not free/paid but:
//
//   free            nothing to pay, end to end (any certificate included)
//   free_cert_paid  the course is free; the CERTIFICATE costs money
//   free_then_paid  free to enter; you pay only if you get through a round
//   freemium        a real free tier, with an optional paid plan on top
//   subscription    you pay per month/year to use it at all
//   one_time        a single up-front fee
//   paid_aid        it costs money, but need-based aid or waivers exist
//   funded          they pay YOU (stipend, or all costs covered)
//   varies          the fee is set by your school/chapter/country, not centrally
//   unknown         we have not verified it — say so, never guess
//
// `unknown` is the default for a reason: an unverified row must say "check the
// official page", never imply free. The discovery pipeline deliberately does NOT
// fill this in — a hallucinated price is worse than no price.
export type CostModel =
  | "free"
  | "free_cert_paid"
  | "free_then_paid"
  | "freemium"
  | "subscription"
  | "one_time"
  | "paid_aid"
  | "funded"
  | "varies"
  | "unknown";

export type Competition = {
  id: string;
  name: string;
  fields: FacultyValue[] | "all";
  deadline: string; // ISO YYYY-MM-DD — registration / submission cutoff
  window: string; // human-readable timing of the event itself
  level: CompetitionLevel;
  category?: CompetitionCategory;
  tier?: CompetitionTier;
  /**
   * Put this above everything else on the list, ahead of fit and deadline.
   *
   * An editorial override, and the only one in the matching engine — everything
   * else about the order is derived. It exists for the case the ordering cannot
   * express: something happening imminently that we want a student to see the
   * moment they open the page, usually because we know about it before any
   * ranking signal does.
   *
   * It does NOT bypass eligibility. A pinned row a student cannot enter is
   * filtered out exactly like any other, because "pinned" is about ORDER and
   * eligibility is about truth — an entry that says "you can enter this" when
   * you cannot is the one failure this product does not get to make.
   *
   * Use it for one thing at a time. A list where everything is pinned is a list
   * with no order at all.
   */
  pinned?: boolean;
  // True only when `deadline` is a real, sourced date for the CURRENT cycle.
  // When false/absent the date is an estimate (or the cycle isn't published yet)
  // and the UI says "Dates not yet announced" instead of showing a countdown we
  // can't stand behind — students must never miss a deadline because of a guess.
  // The scraper can flip this to true (with guardrails); it never silently
  // overwrites a curated date with an unconfirmed scrape (see resolveCompetitions).
  dateConfirmed?: boolean;
  // Who can enter — the age/grade gate, shown on EVERY opportunity card.
  // Phrased exactly as the organizer defines it (ages where the rule is an age,
  // grades where it's a grade); "no minimum" is stated explicitly, and entries
  // we could not verify say so and point to the official page. Checked against
  // official eligibility pages 2026-07-02 — re-verify with the annual date pass.
  eligibility?: string;
  // Geographic scope. Absent/null = global (the whole curated registry).
  // An ISO-2 code ("KZ") marks a LOCAL opportunity — shown only to students
  // whose own country matches, so a Tashkent hackathon never lands on an
  // Almaty student's list and vice versa. `city` narrows the badge further.
  region?: string | null;
  city?: string | null;
  /**
   * Structured entry rules. Normally derived from `eligibility` by
   * parseEligibility(); set explicitly only when that sentence cannot express
   * the rule. An explicit gate always wins over the parsed one.
   */
  gate?: EligibilityGate;
  url: string;
  blurb: string;
  /**
   * There is no deadline, because none exists — a self-paced course, a journal
   * with rolling submissions, a platform running contests all year. These used
   * to render as "dates for the next cycle not announced", which is not a
   * cautious statement but a false one: nothing is going to be announced, and
   * the student can start today. They are the most actionable rows we have and
   * were being presented as the least.
   */
  alwaysOpen?: boolean;
  /**
   * What taking part actually costs. Absent = "unknown" — the UI then says we
   * haven't verified it and points at the official page, which is the only
   * honest thing to render for a row we can't stand behind.
   * Prices checked 2026-08 — re-verify with the annual date pass.
   */
  cost?: CostModel;
  /**
   * One concrete sentence about the money: what's free, what isn't, what aid
   * exists. Figures are approximate on purpose (they drift between cycles) and
   * the UI always pairs them with "confirm on the official page".
   */
  costDetail?: string;
  /**
   * Set when the organisation itself posted this from a partner account, and
   * the reason the row can be trusted differently from a scraped one: the
   * deadline is a first-party statement, not something we extracted from a
   * page. Absent on every curated entry — we never claim someone posted a row
   * we wrote ourselves.
   */
  partner?: PartnerRef;
};

/** Resolved tier — falls back from `level` when a row predates the column. */
export function competitionTier(c: Competition): CompetitionTier {
  if (c.tier) return c.tier;
  return c.level === "international"
    ? "elite"
    : c.level === "national"
      ? "selective"
      : "accessible";
}

/** Resolved category — defaults to "competition" for rows without the column. */
export function competitionCategory(c: Competition): CompetitionCategory {
  return c.category ?? "competition";
}

/**
 * Resolved cost, ready to render: a short pill label, a full sentence, and a
 * tone the UI colours by.
 *
 * `tone` is deliberately three-valued rather than free/paid — "free to learn,
 * paid certificate" is the case students get burned by, and it has to be
 * visually distinct from both. Colour never carries the meaning alone; the
 * label always says the same thing in words.
 */
export type CostTone = "free" | "partial" | "paid" | "unknown";

export type CostInfo = {
  model: CostModel;
  /** Full badge text for the detail panel heading. */
  label: string;
  /** Compact badge text for a card in a list. */
  short: string;
  /** The full, honest sentence for the detail panel. */
  detail: string;
  tone: CostTone;
};

export { opportunityCost, formatDate } from "./opportunity-format";

// The catalog itself lives in competitions-data.ts; re-export it here so the
// public surface of @/lib/data/key-dates is unchanged.
export { COMPETITIONS };

/** Registry lookup by id. Exported so metrics can name what a stored
 *  `opportunity_id` actually refers to (see /admin/intents). */
export const COMPETITION_BY_ID = new Map(COMPETITIONS.map((c) => [c.id, c]));

/**
 * Ids removed from the registry that must never come back.
 *
 * A live row whose id is not in the registry is treated as a genuine addition
 * and appended (that's how discovery ships new opportunities). So deleting a
 * curated entry is not enough: if the scraper has ever written that id to the
 * DB, dropping it here would resurrect it as a live-only row. Retiring the id
 * closes that door.
 */
const RETIRED_IDS = new Set([
  "lumiere-research", // duplicate of "lumiere" — same program, same URL
  "nytimes-stem-writing", // one of the contests listed by "nyt-contests"
]);

/**
 * The full competition list to plan from. The curated registry is the
 * AUTHORITATIVE BASE (every competition we know about always shows, even before
 * the DB is seeded), and a live row from Supabase overlays its date ONLY when
 * the scraper has marked it `dateConfirmed` — i.e. it found a real, in-range
 * date for the current cycle. An unconfirmed live row (a stale seed, or a scrape
 * that wasn't trustworthy) is IGNORED, so a bad/auto date can never silently
 * replace a curated one and push a student past a real deadline. Live-only rows
 * (added straight to the DB) are appended as-is.
 */
export function resolveCompetitions(live?: Competition[]): Competition[] {
  if (!live || live.length === 0) return COMPETITIONS;
  const liveById = new Map(live.map((c) => [c.id, c]));
  const merged = COMPETITIONS.map((c) => {
    const l = liveById.get(c.id);
    return l && l.dateConfirmed
      ? { ...c, deadline: l.deadline, window: l.window, dateConfirmed: true }
      : c;
  });
  for (const l of live) {
    if (!COMPETITION_BY_ID.has(l.id) && !RETIRED_IDS.has(l.id)) merged.push(l);
  }
  return merged;
}

// ── Date helpers (UTC, date-only — no timezone drift) ─────────────────────────
function toUTC(d: Date | string): number {
  const x = typeof d === "string" ? new Date(d + "T00:00:00Z") : d;
  return Date.UTC(x.getUTCFullYear(), x.getUTCMonth(), x.getUTCDate());
}

/** Whole days from `from` to `to` (negative if `to` is in the past). */
export function daysBetween(from: Date | string, to: Date | string): number {
  return Math.round((toUTC(to) - toUTC(from)) / 86_400_000);
}

// ── The engine: build a dated study plan from today + the student's profile ───
export type StudyPlanInputs = {
  today: Date;
  graduationYear?: number;
  faculties: string[];
  satScore?: number;
  // Student's ISO-2 country — gates LOCAL (region-tagged) competitions.
  homeCountry?: string | null;
  // Live data from Supabase (injected by the dashboard layout). When provided,
  // these override the hardcoded SAT_SITTINGS / COMPETITIONS arrays.
  liveSatSittings?: SatSitting[];
  liveCompetitions?: Competition[];
};

export type SatStep = {
  test: string;
  regDeadline: string;
  daysToDeadline: number;
  registrationOpen: boolean; // deadline hasn't passed
  lastBeforeApps: boolean; // last sitting whose scores land before app deadlines
};

export type CompetitionStep = Competition & { daysToDeadline: number };

export type Deadline = { label: string; date: string; daysLeft: number };

export type StudyPlan = {
  cycleLabel: string | null;
  satScore?: number;
  satStrong: boolean; // already a strong score → SAT is optional polish
  satSteps: SatStep[];
  competitions: CompetitionStep[];
  deadlines: Deadline[];
};

const SAT_STRONG = 1500;

export function buildStudyPlan({
  today,
  graduationYear,
  faculties,
  satScore,
  homeCountry,
  liveSatSittings,
  liveCompetitions,
}: StudyPlanInputs): StudyPlan {
  // Use live data when available, fall back to hardcoded arrays. Competitions
  // use the registry as the base with live dates overlaid, so the full curated
  // list always shows (not just whatever's been seeded into the DB).
  const sittings =
    liveSatSittings && liveSatSittings.length > 0
      ? liveSatSittings
      : SAT_SITTINGS;
  const comps = resolveCompetitions(liveCompetitions);

  // Application-deadline window from graduation year. A "Class of G" student
  // applies in the fall before — Early ≈ Nov 1 (G-1), Regular ≈ Jan 5 (G).
  let deadlines: Deadline[] = [];
  let earlyDeadlineISO: string | null = null;
  let cycleLabel: string | null = null;
  if (graduationYear) {
    earlyDeadlineISO = `${graduationYear - 1}-11-01`;
    const regularISO = `${graduationYear}-01-05`;
    cycleLabel = `Class of ${graduationYear} · applying in the ${graduationYear - 1}–${String(
      graduationYear,
    ).slice(2)} cycle`;
    deadlines = [
      {
        label: "Early Action / Decision deadline",
        date: earlyDeadlineISO,
        daysLeft: daysBetween(today, earlyDeadlineISO),
      },
      {
        label: "Regular Decision deadline",
        date: regularISO,
        daysLeft: daysBetween(today, regularISO),
      },
    ].filter((d) => d.daysLeft >= -30); // hide deadlines well in the past
  }

  // SAT sittings whose registration is still open, soonest first. The "last
  // before apps" sitting is the latest test ≥ 3 weeks before the early deadline
  // (scores need time to arrive).
  const openSittings = sittings.filter(
    (s) => daysBetween(today, s.regDeadline) >= 0,
  );
  let lastBeforeIdx = -1;
  if (earlyDeadlineISO) {
    for (let i = 0; i < openSittings.length; i++) {
      if (daysBetween(openSittings[i].test, earlyDeadlineISO) >= 21)
        lastBeforeIdx = i;
    }
  }
  const satSteps: SatStep[] = openSittings.slice(0, 3).map((s, i) => ({
    test: s.test,
    regDeadline: s.regDeadline,
    daysToDeadline: daysBetween(today, s.regDeadline),
    registrationOpen: true,
    lastBeforeApps: i === lastBeforeIdx,
  }));

  // Competitions matching the student's field(s), nearest deadline first. The
  // Timeline is a DATED plan with countdowns, so it only carries competitions
  // whose date is confirmed — never a "typically November" estimate. The full
  // catalog (incl. not-yet-announced ones) lives in the Opportunities section.
  const fac = new Set(faculties);
  const competitions: CompetitionStep[] = comps
    .filter((c) => reachableFrom(c, homeCountry))
    .filter((c) => c.fields === "all" || c.fields.some((f) => fac.has(f)))
    .filter((c) => c.dateConfirmed && daysBetween(today, c.deadline) >= 0)
    .map((c) => ({ ...c, daysToDeadline: daysBetween(today, c.deadline) }))
    .sort((a, b) => a.daysToDeadline - b.daysToDeadline)
    .slice(0, 4);

  return {
    cycleLabel,
    satScore,
    satStrong: satScore != null && satScore >= SAT_STRONG,
    satSteps,
    competitions,
    deadlines,
  };
}

// ── Extracurriculars: strength-matched competition/olympiad recommendations ───
// The idea (founder's): a student with little to show should see ACCESSIBLE
// events to build experience; a strong student doesn't need more entries, they
// need one elite win — so we surface only the top tier for them. "Strength" here
// is the student's extracurricular standing, read off the same rubric factors
// the scorecard uses, not the overall academic score.

const clamp10 = (x: number) => Math.max(0, Math.min(10, x));

/**
 * Extracurricular strength on a 0–10 scale from the profile factors. Achievements
 * weigh most (awards), then sustained activity depth, then academics as a small
 * baseline — the same blend the HK board / scorecard use for "achievements".
 */
export function extracurricularStrength(
  factors: { key: string; score: number }[],
): number {
  const get = (k: string) => factors.find((f) => f.key === k)?.score ?? 0;
  return clamp10(
    0.45 * get("awards") +
      0.35 * get("extracurricular_depth") +
      0.2 * get("academics"),
  );
}

export type StrengthBand = "emerging" | "developing" | "competitive" | "elite";

export function strengthBand(strength: number): StrengthBand {
  if (strength < 4) return "emerging";
  if (strength < 6) return "developing";
  if (strength < 8) return "competitive";
  return "elite";
}

// Which tiers each band should focus on. Emerging students build a record on
// accessible events; the strongest chase only elite ("one clean win").
const BAND_TIERS: Record<StrengthBand, CompetitionTier[]> = {
  emerging: ["accessible"],
  developing: ["accessible", "selective"],
  competitive: ["selective", "elite"],
  elite: ["elite"],
};

const TIER_RANK: Record<CompetitionTier, number> = {
  accessible: 0,
  selective: 1,
  elite: 2,
};

// How an opportunity relates to the student's target band:
//  • recommended — in their band (do these now)
//  • stretch     — above their band (aspirational, worth a look)
//  • foundational— below their band (a strong student has likely outgrown it)
export type OpportunityFit = "recommended" | "stretch" | "foundational";

export type Opportunity = Competition & {
  daysToDeadline: number;
  tierResolved: CompetitionTier;
  categoryResolved: CompetitionCategory;
  fit: OpportunityFit;
  /**
   * Set when the student is not old enough / far enough through school YET.
   * We keep these visible on purpose — knowing what to aim for is the point
   * for a younger student — but they can never be "recommended".
   */
  notYetEligible?: string;
  /** Entry runs through a national team rather than a direct application. */
  viaNationalSelection?: boolean;
};

export type ExtracurricularsPlan = {
  strength: number;
  band: StrengthBand;
  targetTiers: CompetitionTier[];
  items: Opportunity[];
};

const FIT_ORDER: Record<OpportunityFit, number> = {
  recommended: 0,
  stretch: 1,
  foundational: 2,
};

/**
 * Field-matched competitions/olympiads, each tagged with how it fits the
 * student's strength, sorted recommended-first then by nearest deadline. The
 * view groups/filters from this; the matching is all deterministic.
 */
/**
 * Can a student in `homeCountry` reach this opportunity?
 *
 * Three cases, and the middle one is the fix:
 *
 *  • no `region` tag        → global, always shown.
 *  • `region` set, country UNKNOWN → **shown**. An unknown fact must not remove
 *    something from the list, which is the rule the whole matching engine
 *    already runs on: empty faculties means "show everything", an unknown grade
 *    never excludes. Country was the one place that broke it, and the effect was
 *    the worst possible one — a logged-out visitor is exactly who a local event
 *    is FOR, and they were the only person who could not see it. A Shymkent
 *    tournament was invisible in Shymkent until you made an account.
 *  • `region` set, country known and different → hidden. This is the part worth
 *    keeping: a student in Rome should not be offered a one-day event in
 *    Kazakhstan, and once we know where they are we can say so.
 *
 * A local row still carries its city badge, so a visitor whose country we do not
 * know can see at a glance that it is in Shymkent and judge for themselves —
 * which is more respect than hiding it paid them.
 */
export function reachableFrom(
  c: Pick<Competition, "region">,
  homeCountry?: string | null,
): boolean {
  if (!c.region) return true;
  if (!homeCountry) return true;
  return c.region === homeCountry;
}

export function buildExtracurriculars({
  today,
  faculties,
  factors,
  liveCompetitions,
  homeCountry,
  graduationYear,
}: {
  today: Date;
  faculties: string[];
  factors: { key: string; score: number }[];
  liveCompetitions?: Competition[];
  // Student's ISO-2 country (normalized). Local (region-tagged) opportunities
  // only surface when they match it; global ones always do — and it also gates
  // country-restricted entries (US-only competitions etc.).
  homeCountry?: string | null;
  // Drives the school-grade gate (a 9th grader shouldn't be "recommended" a
  // final-year-only programme).
  graduationYear?: number;
}): ExtracurricularsPlan {
  const comps = resolveCompetitions(liveCompetitions);
  const strength = extracurricularStrength(factors);
  const band = strengthBand(strength);
  const targetTiers = BAND_TIERS[band];
  const targetMax = Math.max(...targetTiers.map((t) => TIER_RANK[t]));
  const fac = new Set(faculties);
  const grade = gradeFromGraduationYear(graduationYear, today);

  const items: Opportunity[] = comps
    .filter((c) => reachableFrom(c, homeCountry))
    // An empty field selection means "we don't know yet", not "show almost
    // nothing". Filtering on it left a profile-less student with 9 of 86
    // opportunities — the exact dead end that makes people leave.
    .filter(
      (c) =>
        fac.size === 0 ||
        c.fields === "all" ||
        c.fields.some((f) => fac.has(f)),
    )
    // Drop a CONFIRMED competition once its date has passed. Keep
    // not-yet-announced ones (the catalog shows them as "Dates not yet
    // announced") — their stored date is only an estimate, so we don't filter on
    // it and we never present it as a hard deadline.
    .filter((c) => !c.dateConfirmed || daysBetween(today, c.deadline) >= 0)
    // Eligibility gate. A student in Kazakhstan was being recommended
    // "Grades 9–12 at a US school" competitions, and a 9th grader was being
    // recommended final-year-only programmes. Unknown facts never exclude.
    .map((c) => {
      const gate = c.gate ?? parseEligibility(c.eligibility);
      // Age rules were being ignored entirely — we only ever passed the school
      // year, so every "Ages 13–18" entry counted as open to a 12-year-old and
      // the count we showed them was wrong. We still never ask for a birth
      // date, so age comes from the year group as a RANGE and only excludes
      // when the whole group is outside the rule.
      const verdict = checkEligibility(gate, {
        country: homeCountry,
        grade,
        ageRange: grade == null ? null : plausibleAgeForGrade(grade),
      });
      return { c, gate, verdict };
    })
    // Can never enter: wrong country, or already past the age/grade ceiling.
    .filter(({ verdict }) => verdict.ok || verdict.reason === "too_young")
    .map(({ c, gate, verdict }) => {
      const tierResolved = competitionTier(c);
      const notYetEligible = verdict.ok ? undefined : verdict.detail;
      // Not yet eligible is always aspirational, never "do this now".
      const fit: OpportunityFit = notYetEligible
        ? "stretch"
        : targetTiers.includes(tierResolved)
          ? "recommended"
          : TIER_RANK[tierResolved] > targetMax
            ? "stretch"
            : "foundational";
      return {
        ...c,
        daysToDeadline: daysBetween(today, c.deadline),
        tierResolved,
        categoryResolved: competitionCategory(c),
        fit,
        notYetEligible,
        viaNationalSelection: gate.viaNationalSelection,
      };
    })
    .sort((a, b) => {
      // The one editorial override, ahead of fit. Everything below this line is
      // derived from the student's own profile; this line is us saying "look at
      // this first". It only reorders what already passed eligibility.
      const ap = a.pinned ? 0 : 1;
      const bp = b.pinned ? 0 : 1;
      if (ap !== bp) return ap - bp;
      if (FIT_ORDER[a.fit] !== FIT_ORDER[b.fit])
        return FIT_ORDER[a.fit] - FIT_ORDER[b.fit];
      // Confirmed-date items first (actionable now), then "dates TBA".
      const ac = a.dateConfirmed ? 0 : 1;
      const bc = b.dateConfirmed ? 0 : 1;
      if (ac !== bc) return ac - bc;
      return a.daysToDeadline - b.daysToDeadline;
    });

  return { strength, band, targetTiers, items };
}
